### PR TITLE
Add request to ApiException

### PR DESCRIPTION
**Pull request by sandervanhooft**
Adds a `getRequest` method to `ApiException`.

Solves #472

### CODE REVIEW

**Comment by willemstuursma** [comment]
We should add the local time.

**Comment by sandervanhooft** [comment]
> We should add the local time.

Sure. In Iso 8601 string or in php DateTime?

**Comment by willemstuursma** [comment]
ISO is great. This PR is also missing the part where the request body is added to the exception message. 

The exception messages are often shared with us by merchants, so it is convenient if they contain more data to help track problems (so we don't have to ask for it).

**Comment by sandervanhooft** [comment]
@willemstuursma Added both the dateTime iso string and the request body to the exception object and message.

Let me know if it can be merged and I'll release it.

**Comment by willemstuursma** [comment]
@sandervanhooft I made some more changes. If you concur, it can be released.

**Comment by sandervanhooft** [comment]
Thanks @willemstuursma , looks good to me! I'll schedule a release tomorrow.

**Comment by lode** [comment]
This PR made it a little harder for us to recognize errors and act upon them.

Before this PR we checked the exception message. While maybe not perfect, it was the only thing we had which gave some information. With this PR the timestamp is added to that making it harder for us to auto determine what to do based on the message.

We now can use something like `json_decode($e->getResponse()->getBody()->__toString(), true)['detail']`. But it would be nice if there was a public interface on the exception object to get to the response json (or its actual fields) in a bit more stable way for which we don't have to know how the exception object works internally.

**Pull request merged**
