### PR TITLE
Reorder and modernize Travis config

### PR DESCRIPTION
**Pull request by szepeviktor**
actually in execution order

### CODE REVIEW

**Comment by willemstuursma** [comment]
LGTM, what do you think @sandervanhooft ?

**Comment by sandervanhooft** [comment]
LGTM!

Perhaps add PHP 7.4 support while we're at it?

**Comment by szepeviktor** [comment]
Done :)

**Comment by sandervanhooft** [comment]
Thanks @szepeviktor !

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
