### PR TITLE
Travis: allow PHP nightly to fail and switch to xenial images

### PR DESCRIPTION
**Pull request by firstred**
Removing PHP nightly from the original array, but keeping it under `allow_failures` will allow it to fail.

### CODE REVIEW

**Comment by firstred** [comment]
Nope, that does not work. We should go for matrix builds. New commits coming soon!

**Comment by firstred** [comment]
Using a build matrix for all PHP versions should fix it.

**Comment by firstred** [comment]
Hmmz, these are the same results I see in my repo. It turns out that testing on xenial is more stable, which makes sense since trusty has been deprecated for a while already.

One more test, just to see if everything can be moved to the xenial images.

**Comment by firstred** [comment]
Alrighty, that works! Enjoy a new, more stable testing experience! :slightly_smiling_face:

**Comment by willemstuursma** [comment]
Cool, opened https://github.com/composer/ca-bundle/pull/34.

**Pull request merged**
