### PR TITLE
fix: wrong phpdoc return for cancelFor/cancelForId methods

### PR DESCRIPTION
**Pull request by mheiduk**
the return for the subscription methods cancelFor/cancelForId in phpdoc comments is wrong. instead of null it should be mixed.

see https://docs.mollie.com/reference/cancel-subscription

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Hi @mheiduk ,

Thanks for the PR.

On this package the return value actually is `null` here.

**Comment by mheiduk** [comment]
With the `cancelForId` method I get a response like the documentation says:

```php
$subscription = $this->mollie->subscriptions->cancelForId($customer_id, $subscription_id);
return rest_ensure_response(['status' => $subscription->status]);
```

response is in this case:

```json
{
  "status": "canceled"
}
```

**Comment by mheiduk** [comment]
push @sandervanhooft 

would be great if you can take a second look at this.

**Comment by sandervanhooft** [comment]
@mheiduk turns out you're right! 😅  Sorry about that.

**Comment by sandervanhooft** [comment]
I'd prefer to change the return type to `Subscription` here though.

**Comment by sandervanhooft** [comment]
`Mollie\Api\Resources\Subscription`

**Comment by mheiduk** [comment]
@sandervanhooft thanks, changed it to Subscription

**Comment by sandervanhooft** [comment]
Thanks @mheiduk, released it just now!

https://github.com/mollie/mollie-api-php/releases/tag/v2.74.0

**Pull request merged**
