### PR TITLE
Added forId methods in SubscriptionEndpoint

### PR DESCRIPTION
**Pull request by Rkallenkoot**
Makes it consistent with the CustomerPaymentsEndpoint, saves a couple API calls when dealing with Subscriptions directly

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Thanks @Rkallenkoot ! Can you ensure it's covered by tests?

**Comment by Rkallenkoot** [comment]
Sure, could you perhaps point out where `getFor` and such are tested so I have a point of reference?

**Comment by sandervanhooft** [comment]
Easiest may be this approach (similar for other methods)

`getFor` is using `getForId` under the hood. If you refactor it that way, the existing tests for `getFor` will cover `getForId` as well.

**Comment by sandervanhooft** [comment]
I.e. https://github.com/mollie/mollie-api-php/blob/65eb23e49725c13f9453d1c209d240d02add1be7/src/Endpoints/PaymentCaptureEndpoint.php#L44-L62

**Comment by Rkallenkoot** [comment]
I'm not sure `getFor` etc are tested for Subscriptions btw!

**Comment by Rkallenkoot** [comment]
Added methods are already covered :+1:

**Comment by Rkallenkoot** [comment]
Let me know if I can assist in any way to get this merged!

**Comment by sandervanhooft** [comment]
Thanks @Rkallenkoot ! Will be included in upcoming release.

**Pull request merged**
