### PR TITLE
Add phpstan to CI

### PR DESCRIPTION
**Pull request by nederdirk**
As suggested by @willemstuursma, here is a patch that adds phpstan to the travis definition. To pass phpstan level 1, I also had to make a couple of changes, mainly in type definitions and erroneous function calls.

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Nice! Can we help contributors run this locally too? (I.e. instructions, pre-commit hook) I for one haven't used it before.

**Comment by sandervanhooft** [comment]
Some issues with PHP versions 5.6, 7 and 7.1. @nederdirk is this something that you can fix?

I'd love to keep full backwards compatibility.

**Comment by szepeviktor** [comment]
PHPStan should be ran only once, for example with PHP 7.3
The code it checks could run on any PHP version.

**Comment by nederdirk** [comment]
@sandervanhooft I finally have gotten around to getting this done. It took some awkward fiddling with `composer.json` and `.travis.yml` to get it to work with old PHP versions

**Comment by sandervanhooft** [comment]
@nederdirk That's great, thanks!

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
