### PR TITLE
Fix minor mistakes in endpoint tests

### PR DESCRIPTION
**Pull request by Pimm**
Hi everyone, you look great! Did you do something with your hair?

As I was porting tests to the Node.js-client, I noticed some things that I think are mistakes.

**Please verify**.

### CODE REVIEW

**Comment by sandervanhooft** [comment]
I prefer the current `webhookUrl` and `redirectUrl` for readability. Can you revert these?

The other changes look good to me!

**Comment by Pimm** [comment]
> I prefer the current `webhookUrl` and `redirectUrl` for readability. Can you revert these?

I personally don't care what the URLs are. It's just that currently, the URLs which are `POST`ed are not equal to the ones which are replied.

(Check out [CustomerPaymentEndpointTest.php](https://github.com/mollie/mollie-api-php/blob/master/tests/Mollie/API/Endpoints/CustomerPaymentEndpointTest.php#L16): it `POST`s `https://example.org/webhook` and then replies `http://example.org/examples/payment/02-webhook-verification.php`).

**Comment by vernondegoede** [comment]
I agree with @sandervanhooft – I'd prefer the old URLs. While you're at it, could you update the URLs in the assertions as well?

**Comment by Pimm** [comment]
Sure. Again, I am not advocating for one URL or the other. What I wanted to fix was the test `POST`ing `https://example.org/webhook` and then replying `http://example.org/examples/payment/02-webhook-verification.php`. Those two should be equal, whatever they might be.

**Comment by sandervanhooft** [comment]
LGTM, thanks @Pimm !

**Pull request merged**
