### PR TITLE
Changes to method resource (min|max) and endpoint (docblocks)

### PR DESCRIPTION
**Pull request by sandervanhooft**
Conform Changelog [here](https://docs.mollie.com/changelog/v2/changelog#wednesday-27th).

### CODE REVIEW

**Comment by sandervanhooft** [comment]
@MollieRick What response does the Method endpoint return for `giftcard`? Is `minimumAmount`, `maximumAmount` included as well here?

**Comment by sandervanhooft** [comment]
There are no minima/maxima listed here for `giftcards`: https://help.mollie.com/hc/en-us/articles/115000667365-What-are-the-minimum-and-maximum-amounts-per-payment-method .

**Comment by MollieRick** [comment]
Hi Sander,

We do return minima/maxima for `giftcards`, but it can be a weird amount. For example:
```
{
   "resource":"method",
   "id":"giftcard",
   "description":"VVV Cadeaukaart",
   "minimumAmount":{
      "value":"0.01",
      "currency":"EUR"
   },
   "maximumAmount":{
      "value":"92233720368549856.00",
      "currency":"EUR"
   },
   "image":{
      "size1x":"https://www.mollie.com/external/icons/giftcard-issuers/vvvgiftcard.png",
      "size2x":"https://www.mollie.com/external/icons/giftcard-issuers/vvvgiftcard%402x.png",
      "svg":"https://www.mollie.com/external/icons/giftcard-issuers/vvvgiftcard.svg"
   },
   "_links":{
      "self":{
         "href":"https://api.mollie.com/v2/methods/giftcard",
         "type":"application/hal+json"
      }
   }
}
```

**Comment by willemstuursma** [comment]
This looks like a bug @MollieRick.

**Comment by sandervanhooft** [comment]
I need new friends, I never get giftcards looking like that ;)

**Comment by sandervanhooft** [comment]
I'm asking because I want to keep the test responses ([here](https://github.com/mollie/mollie-api-php/pull/373/files#diff-fe37a41a2d71471fe2cf7c0666a0f7cf)) in sync before merging.

**Comment by sandervanhooft** [comment]
Regarding this example: vvvcadeaukaarten.nl sells vvv giftcards up to €250.

**Comment by sandervanhooft** [comment]
Just talked to Rick, I'll use €150 in the example.

**Comment by MollieRick** [comment]
It is a bug, will be fixed today!

**Comment by sandervanhooft** [comment]
Included a docblock instruction on using `profileId` when using OAuth Access Tokens.

**Pull request merged**
