### PR TITLE
Fix empty subresource collection issue

### PR DESCRIPTION
**Pull request by sandervanhooft**
#423

### CODE REVIEW

**Comment by sandervanhooft** [comment]
I've expanded the scope to all calls made to `ResourceFactory::createBaseResourceCollection`.

**Comment by sandervanhooft** [comment]
I'd prefer to set the array as a default value...

```php
class Method extends BaseResource {

public $issuers = [];

}
```

... but this could cause issues in existing integrations. So tackling this in  `ResourceFactory::createBaseResourceCollection` calls instead.

**Comment by sandervanhooft** [comment]
@MollieRick Ready for release? (minor patch)

**Comment by willemstuursma** [comment]
It might make more sense to update `createBaseResourceCollection` lest any callers forget to implement `?: []`.

**Comment by sandervanhooft** [comment]
@willemstuursma Agreed. All done!

**Pull request merged**
