### PR TITLE
Updated tests and optimisation

### PR DESCRIPTION
**Pull request by ptondereau**
I've refactored some tests due to deprecated warnings for `getMock()` and `setExpectedException()` methods.

I also updated `.travis.yml` to enable PHP 7 and old PHP versions.

Finally, I replaced all double quotes by single one when it's needed (performance).

Suggests: 

- use [StyleCI](https://styleci.io/)
- I can prepare your .travis.yml for automatically use [Scrutinizer](https://scrutinizer-ci.com/) (SaaS code metrics viewer instead of phpunit coverage)
- Force users to use only PHP >= 5.5.9 because of security issues and to only use PHPUnit >= 4.8 for you 😉 .

### CODE REVIEW

**Comment by RicardoJ** [comment]
Thank you for your -really- appreciated pull request @ptondereau! 👍

I've have reviewed your pull request, while I agree totally on your changes, I'll let some other people review this.

Thank you again!

**Comment by ptondereau** [comment]
Is there anything wrong ?

**Comment by RickWong** [comment]
Hi Pierre. There's nothing wrong but we kinda have extreme lots of work to do currently. We haven't had time to merge this yet.

**Comment by ptondereau** [comment]
@RickWong Ok no problem. Good luck

**Comment by mollierobbert** [comment]
Hey Pierre, sorry for the long wait. We've just squash merged your changes and fixed some more minor PHPUnit issues.

We didn't end up using your changes in quoting style though, since this is a matter of preference. The difference in performance is negligible.

Thanks again for your help.

**Pull request merged**
