### PR TITLE
Add onboarding endpoint

### PR DESCRIPTION
**Pull request by LauLaman**
Add implementation for the new [onboarding endpoint](https://docs.mollie.com/reference/v2/onboarding-api/get-onboarding-status)

_Remark:_
The onboarding endpoint has no collection of resources therefore i extracted that logic to  `CollectionEndpointAbstract`

### CODE REVIEW

**Comment by sandervanhooft** [comment]
@LauLaman 

Thanks!

Ok, just to get things clear. There are two things going on here:

1. Adding the Onboarding Endpoint.
2. Splitting the former EndpointAbstract into a CollectionEndpointAbstract and a stripped-down EndpointAbstract, so the latter better fits the new Onboarding Endpoint.

Correct?

**Comment by LauLaman** [comment]
@sandervanhooft 

1. Yes, one remark:
Unfortunately i had to overwrite the `rest_read` and `rest_create` methods since the onboarding Api does not play nice with the current implementation 

2. Yeah i did not wanna implement the abstract method `getResourceCollectionObject` in the Onboarding endpoint that does do nothing.  So i moved that to its own abstract class

**Comment by sandervanhooft** [comment]
Ok clear @LauLaman , thanks. I agree your refactor provides more clarity.

I'll look into this; there are some other places where `rest_read` and `rest_create` are circumvented.
I.e. for calling `/methods/all`.

**Comment by ChristianVermeulen** [comment]
@sandervanhooft In order to be able to actually use this I've added the permission constants in the oauth repo: https://github.com/mollie/oauth2-mollie-php/pull/15.

However, the last time tests ran for that repo was 6 months ago and it now seems like the php nightly tests are failing due to changes at travis. There is actually a second PR open with even more permission constants.

Perhaps you guys can add this with suitable priority on the board to get this merged as well? :D

**Comment by sandervanhooft** [comment]
Hi @ChristianVermeulen,

Thanks for getting me in the loop, wasn't involved yet in the oauth package. Will look into this this afternoon!

**Pull request merged**
